-- AlterTable
ALTER TABLE "Moliya" ALTER COLUMN "All_Kirim" SET DATA TYPE TEXT,
ALTER COLUMN "All_Chiqim" SET DATA TYPE TEXT,
ALTER COLUMN "foyda" SET DATA TYPE TEXT,
ALTER COLUMN "summa" SET DATA TYPE TEXT;
